services:
  backend:
  build: ./backend
  container_name: mern-backend
  ports:
    - "5000:5000"
  environment:
    PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
    JWT_SECRET: ${JWT_SECRET}
    MONGO_URL: ${MONGO_URL}
  restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: unless-stopped

  admin:
    build: ./admin
    container_name: mern-admin
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
